import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/header/Header";
import Footer from "./_components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />
        <main className=" container mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
