import "./globals.css";
import Header from "./_components/header/Header";
import Footer from "./_components/Footer";
import { CartContextProvider } from "./_context/CartContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <CartContextProvider>
          <Header />
          <main className=" container mx-auto">{children}</main>
          <Footer />
        </CartContextProvider>
      </body>
    </html>
  );
}
